### ISSUE TITLE
pty.js  Cannot find module '../bin/linux/x64.node' version 1.12.7

### ISSUE THREAD

**Issue by brucezlata** [jeremyramin/terminal-plus#412]
terminal-plus is broken after upgrading atom to 1.12.7. It report "pty.js  Cannot find module '../bin/linux/x64.node' version 1.12.7".

I tried to copy release/pty.node to bin/linux/x64.node in pty.js and rebuild atom. But it also failed.

**Comment by brucezlata** [comment]
My OS is Ubuntu 16.04 64 bits. Any one can find the workaround or solution?
