### ISSUE TITLE
It didn't work on Atom 1.19.2 x64

### ISSUE THREAD

**Issue by JZLeung** [jeremyramin/terminal-plus#508]
Error
```
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
```

```
terminal-plus 0.14.5

pty.js@0.3.1 – Cannot find module '../bin/darwin/x64.node'
```

**Comment by rafpyprog** [comment]
Click on "Rebuild Package" button (top right).

**Comment by JZLeung** [comment]
@rafpyprog it can open the terminal now, but can not enter any command.
<img width="453" alt="2017-09-07 9 08 53" src="https://user-images.githubusercontent.com/7995232/30141179-3fdb050c-93ac-11e7-8048-370e5d7081e6.png">

**Comment by renaud-vmg** [comment]
Same issue as @JZLeung here.
